# Miryoku features for KillerWhale DUO
ENCODER_MAP_ENABLE = yes
COMBO_ENABLE = yes
CAPS_WORD_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
MOUSEKEY_ENABLE = yes
OLED_ENABLE = yes
RGBLIGHT_ENABLE = yes
WPM_ENABLE = yes
